### ISSUE TITLE
ORM : add support for conditional delete

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxOrm#11]
We should support conditional remove. 

E.g. `DELETE FROM `bucket` WHERE ( oxDeletable = TRUE AND oxAuthExpiration <= "2019-08-22T16:59:50.553+0000" )`

Idea:
`public <T> boolean deleteEntries(String baseDN, Class<T> entryClass, Filter filter)`

**Comment by yurem** [comment]
Implemented. ORM has method `<T> int remove(String primaryKey, Class<T> entryClass, Filter filter, int count);`
